// Generated by kleverkeys-generator
// For extra security, complete the last return value with a secure random hex value. (32 bytes)

#include "KleverKeys.h"

//E27779D509CDDC3C658F089C561BDA45A4D2E07DDAFE0471FC613514650A5F90
DEFINE_HIDDEN_STRING(String1, 0x33, ('E')('2')('7')('7')('7')('9')('D')('5')('0')('9')('C')('D')('D')('C')('3')('C')('6')('5')('8')('F')('0')('8')('9')('C')('5')('6')('1')('B')('D')('A')('4')('5')('A')('4')('D')('2')('E')('0')('7')('D')('D')('A')('F')('E')('0')('4')('7')('1')('F')('C')('6')('1')('3')('5')('1')('4')('6')('5')('0')('A')('5')('F')('9')('0'))
//0EA267FD5C111372240AFBA51694216F341E35196047F138961D2F82E5174302
DEFINE_HIDDEN_STRING(String2, 0x52, ('0')('E')('A')('2')('6')('7')('F')('D')('5')('C')('1')('1')('1')('3')('7')('2')('2')('4')('0')('A')('F')('B')('A')('5')('1')('6')('9')('4')('2')('1')('6')('F')('3')('4')('1')('E')('3')('5')('1')('9')('6')('0')('4')('7')('F')('1')('3')('8')('9')('6')('1')('D')('2')('F')('8')('2')('E')('5')('1')('7')('4')('3')('0')('2'))
//C911C61C0D7A8D9C807E5B4EA88178C0
DEFINE_HIDDEN_STRING(String3, 0x5E, ('C')('9')('1')('1')('C')('6')('1')('C')('0')('D')('7')('A')('8')('D')('9')('C')('8')('0')('7')('E')('5')('B')('4')('E')('A')('8')('8')('1')('7')('8')('C')('0'))
//A7FB65B1DE5072AE896E4F4C5A7CCB51
DEFINE_HIDDEN_STRING(String4, 0x2B, ('A')('7')('F')('B')('6')('5')('B')('1')('D')('E')('5')('0')('7')('2')('A')('E')('8')('9')('6')('E')('4')('F')('4')('C')('5')('A')('7')('C')('C')('B')('5')('1'))
//2EA7A815E49F63764FA76D554400E384
DEFINE_HIDDEN_STRING(String5, 0x3D, ('2')('E')('A')('7')('A')('8')('1')('5')('E')('4')('9')('F')('6')('3')('7')('6')('4')('F')('A')('7')('6')('D')('5')('5')('4')('4')('0')('0')('E')('3')('8')('4'))
//19C134B2A4A1F8C3E7C2783B34638742
DEFINE_HIDDEN_STRING(String6, 0x5E, ('1')('9')('C')('1')('3')('4')('B')('2')('A')('4')('A')('1')('F')('8')('C')('3')('E')('7')('C')('2')('7')('8')('3')('B')('3')('4')('6')('3')('8')('7')('4')('2'))
//434BAE3DAAFB450EEC81F3B18B1A5A86
DEFINE_HIDDEN_STRING(String7, 0x51, ('4')('3')('4')('B')('A')('E')('3')('D')('A')('A')('F')('B')('4')('5')('0')('E')('E')('C')('8')('1')('F')('3')('B')('1')('8')('B')('1')('A')('5')('A')('8')('6'))
//7FF65F5EA0F87E80D2845E91A0F784A3
DEFINE_HIDDEN_STRING(String8, 0x65, ('7')('F')('F')('6')('5')('F')('5')('E')('A')('0')('F')('8')('7')('E')('8')('0')('D')('2')('8')('4')('5')('E')('9')('1')('A')('0')('F')('7')('8')('4')('A')('3'))
//D14FC9192250440D
DEFINE_HIDDEN_STRING(String9, 0x79, ('D')('1')('4')('F')('C')('9')('1')('9')('2')('2')('5')('0')('4')('4')('0')('D'))
//E3D35C05FB179403
DEFINE_HIDDEN_STRING(String10, 0x6A, ('E')('3')('D')('3')('5')('C')('0')('5')('F')('B')('1')('7')('9')('4')('0')('3'))

std::string KleverKeys::get(std::string id) {

	if(id == "F8923C182CA2AB9A2C30B8174560671A95410BCB77B051EC6161177CB2F664A8") {
		return GetString1();
	} else if(id == "F37E366C080B52156953F088C8F5F7BBD6BE0A814B26D74328136DEE03A34E88") {
		return GetString2();
	} else if(id == "87B4BBF4C1223342BC4A31FC8EB243FA80A1F6ED48E9E7AC8FE608C73288B902") {
		return GetString3();
	} else if(id == "1627D45EB7CD7E6DB68AF27111D7DCFC2BF22C2CF9EB2AF8D215540C3CDA89A4") {
		return GetString4();
	} else if(id == "71F7C3D6F088A31E7D311860E227C1846B889F57EF8BF30DFF06D3BA5E795660") {
		return GetString5();
	} else if(id == "729AAB61E8198BBA81CA25830A440E9C073F2E89454D018720C8BE8C41C0FA5") {
		return GetString6();
	} else if(id == "9A9C1E959C45F0532B51B7C46756BB729A652417DF3ABB15005E20A89D584F25") {
		return GetString7();
	} else if(id == "48329208445A8717684D4430B3996D9927D9E5F26E6B9AA101C149844696E68E") {
		return GetString8();
	} else if(id == "76663A8C739484F84A55540FE3D0358B10A12536FCB633A5EEC744631F919E8") {
		return GetString9();
	} else if(id == "518E10522B59FCB08CEBC59B574BB0B9161D5590CAF99E9DADF0E95028202F78") {
		return GetString10();
	}


	//return new HexSecureRandom();
	return "";


}
