// Generated by kleverkeys-generator

#include "KleverKeys.h"
#include "easy_encrypt/EasyEncrypt.h"

//8CC3C9CE2950AAD15CE64F02119464F3ED2EBADFEF60A43DD03DEB5768F39BC2
DEFINE_HIDDEN_STRING(String1, 0x5F, ('8')('C')('C')('3')('C')('9')('C')('E')('2')('9')('5')('0')('A')('A')('D')('1')('5')('C')('E')('6')('4')('F')('0')('2')('1')('1')('9')('4')('6')('4')('F')('3')('E')('D')('2')('E')('B')('A')('D')('F')('E')('F')('6')('0')('A')('4')('3')('D')('D')('0')('3')('D')('E')('B')('5')('7')('6')('8')('F')('3')('9')('B')('C')('2'))
//302DC94430486B1308E343BBDC64125999658D6940EF8487DD6586A535453688
DEFINE_HIDDEN_STRING(String2, 0x02, ('3')('0')('2')('D')('C')('9')('4')('4')('3')('0')('4')('8')('6')('B')('1')('3')('0')('8')('E')('3')('4')('3')('B')('B')('D')('C')('6')('4')('1')('2')('5')('9')('9')('9')('6')('5')('8')('D')('6')('9')('4')('0')('E')('F')('8')('4')('8')('7')('D')('D')('6')('5')('8')('6')('A')('5')('3')('5')('4')('5')('3')('6')('8')('8'))
//972938098BE4130F9D89026B5A67D64CD650C91F6BA19EAD9AE6DBB4044AFC23
DEFINE_HIDDEN_STRING(String3, 0x0D, ('9')('7')('2')('9')('3')('8')('0')('9')('8')('B')('E')('4')('1')('3')('0')('F')('9')('D')('8')('9')('0')('2')('6')('B')('5')('A')('6')('7')('D')('6')('4')('C')('D')('6')('5')('0')('C')('9')('1')('F')('6')('B')('A')('1')('9')('E')('A')('D')('9')('A')('E')('6')('D')('B')('B')('4')('0')('4')('4')('A')('F')('C')('2')('3'))
//C155DB0C7D5EBAA8AC5C2F6BDB4C5E7B
DEFINE_HIDDEN_STRING(String4, 0x1F, ('C')('1')('5')('5')('D')('B')('0')('C')('7')('D')('5')('E')('B')('A')('A')('8')('A')('C')('5')('C')('2')('F')('6')('B')('D')('B')('4')('C')('5')('E')('7')('B'))
//B2942549BD0726C91E90CBFD09641CCC
DEFINE_HIDDEN_STRING(String5, 0x21, ('B')('2')('9')('4')('2')('5')('4')('9')('B')('D')('0')('7')('2')('6')('C')('9')('1')('E')('9')('0')('C')('B')('F')('D')('0')('9')('6')('4')('1')('C')('C')('C'))
//2CD61B9D749AAD77BCF5BFE8AE5C3A79
DEFINE_HIDDEN_STRING(String6, 0x40, ('2')('C')('D')('6')('1')('B')('9')('D')('7')('4')('9')('A')('A')('D')('7')('7')('B')('C')('F')('5')('B')('F')('E')('8')('A')('E')('5')('C')('3')('A')('7')('9'))
//4372B5D7FFB031C6187946E6DB2E8B9D
DEFINE_HIDDEN_STRING(String7, 0x17, ('4')('3')('7')('2')('B')('5')('D')('7')('F')('F')('B')('0')('3')('1')('C')('6')('1')('8')('7')('9')('4')('6')('E')('6')('D')('B')('2')('E')('8')('B')('9')('D'))
//B3D062CB0866B25CD1B18700CA191D18
DEFINE_HIDDEN_STRING(String8, 0x52, ('B')('3')('D')('0')('6')('2')('C')('B')('0')('8')('6')('6')('B')('2')('5')('C')('D')('1')('B')('1')('8')('7')('0')('0')('C')('A')('1')('9')('1')('D')('1')('8'))
//F4AB16AB6B773AF09222DBE171DF0536
DEFINE_HIDDEN_STRING(String9, 0x25, ('F')('4')('A')('B')('1')('6')('A')('B')('6')('B')('7')('7')('3')('A')('F')('0')('9')('2')('2')('2')('D')('B')('E')('1')('7')('1')('D')('F')('0')('5')('3')('6'))
//AFB16A2A343B5B1A4DD19891238081EF
DEFINE_HIDDEN_STRING(String10, 0x6D, ('A')('F')('B')('1')('6')('A')('2')('A')('3')('4')('3')('B')('5')('B')('1')('A')('4')('D')('D')('1')('9')('8')('9')('1')('2')('3')('8')('0')('8')('1')('E')('F'))

std::string KleverKeys::get(std::string id) {

	std::string upperId = EasyEncrypt::Utils::toUpperCase(id);
	std::string hashedId = EasyEncrypt::Utils::toUpperCase(EasyEncrypt::SHA::hash256((char*) upperId.c_str()));


	if(hashedId == "91D23CC90DFB5CB1A87ED06554F9AE49622661315E3328959405701286AB8A7E") {
		return GetString1();
	} else if(hashedId == "C687CF1596CDBADCDA4B5486768E948C53DA88DC42A8BA5EF5F471111A0711CE") {
		return GetString2();
	} else if(hashedId == "FB8EB49D43F23BC6DBC230E80955077541A525827F9737D1F9D5C94277855465") {
		return GetString3();
	} else if(hashedId == "69AB91B76506768C4918CC684932844F44E7CAB5D601B5825DFAFCE2AEB2D4A9") {
		return GetString4();
	} else if(hashedId == "C3A6D7D55223E3730BD23B56E402B59EBC136FEDB0B1249A911F8A40C877AC73") {
		return GetString5();
	} else if(hashedId == "BE401C82316D2E339DC3184766420802F68925FBC0C9ABD3E68E9B08A00AB8C1") {
		return GetString6();
	} else if(hashedId == "D2B5F0B18B8FA7B2A3EFD07D3D416D997B891E942D95C10EA28C3CF8EEB41C6F") {
		return GetString7();
	} else if(hashedId == "CCE93D7A832A5033DCBFC237932725E4A2AE3E9D81887D3E20175C22069EB9FB") {
		return GetString8();
	} else if(hashedId == "69AAD92647150E790E014711DC6CBFB2BFB70419C56FFB3217315764D78CBDAD") {
		return GetString9();
	} else if(hashedId == "78BFA0789B96E282D27CF1FC24124FB472A058D775C72EC0ECF196A35F3599DF") {
		return GetString10();
	}


	//return a random hex value, disguised as a 32 bit hex key.
	return EasyEncrypt::Utils::toUpperCase((const char*) EasyEncrypt::Random::secureEncoded(32, EasyEncrypt::HEX));


}
