// Generated by kleverkeys-generator
// For extra security, complete the last return value with a secure random hex value. (32 bytes)

#include "KleverKeys.h"

//5B843C1D82919BAF8B7E71463785FBA75ACF47853DF95FE3BA2C10633DBE9A81
DEFINE_HIDDEN_STRING(String1, 0x27, ('5')('B')('8')('4')('3')('C')('1')('D')('8')('2')('9')('1')('9')('B')('A')('F')('8')('B')('7')('E')('7')('1')('4')('6')('3')('7')('8')('5')('F')('B')('A')('7')('5')('A')('C')('F')('4')('7')('8')('5')('3')('D')('F')('9')('5')('F')('E')('3')('B')('A')('2')('C')('1')('0')('6')('3')('3')('D')('B')('E')('9')('A')('8')('1'))
//B0B9449C19A42146852B6FBABB4DE0992501B54CC54AB8D70B190EC0FBE2DEF9
DEFINE_HIDDEN_STRING(String2, 0x25, ('B')('0')('B')('9')('4')('4')('9')('C')('1')('9')('A')('4')('2')('1')('4')('6')('8')('5')('2')('B')('6')('F')('B')('A')('B')('B')('4')('D')('E')('0')('9')('9')('2')('5')('0')('1')('B')('5')('4')('C')('C')('5')('4')('A')('B')('8')('D')('7')('0')('B')('1')('9')('0')('E')('C')('0')('F')('B')('E')('2')('D')('E')('F')('9'))
//131567596967E2678FAFEDFDC2657154
DEFINE_HIDDEN_STRING(String3, 0x08, ('1')('3')('1')('5')('6')('7')('5')('9')('6')('9')('6')('7')('E')('2')('6')('7')('8')('F')('A')('F')('E')('D')('F')('D')('C')('2')('6')('5')('7')('1')('5')('4'))
//E97D3B0110E8F88C410E2583C67EB9CE
DEFINE_HIDDEN_STRING(String4, 0x08, ('E')('9')('7')('D')('3')('B')('0')('1')('1')('0')('E')('8')('F')('8')('8')('C')('4')('1')('0')('E')('2')('5')('8')('3')('C')('6')('7')('E')('B')('9')('C')('E'))
//8314FBCCDD7EAD5064FE84410E2474C5
DEFINE_HIDDEN_STRING(String5, 0x27, ('8')('3')('1')('4')('F')('B')('C')('C')('D')('D')('7')('E')('A')('D')('5')('0')('6')('4')('F')('E')('8')('4')('4')('1')('0')('E')('2')('4')('7')('4')('C')('5'))
//8144AA8014A604DC3E58B2BCAEFC89DA
DEFINE_HIDDEN_STRING(String6, 0x27, ('8')('1')('4')('4')('A')('A')('8')('0')('1')('4')('A')('6')('0')('4')('D')('C')('3')('E')('5')('8')('B')('2')('B')('C')('A')('E')('F')('C')('8')('9')('D')('A'))
//D33B971DAF446269
DEFINE_HIDDEN_STRING(String7, 0x27, ('D')('3')('3')('B')('9')('7')('1')('D')('A')('F')('4')('4')('6')('2')('6')('9'))
//62CD6973BC3BDD80
DEFINE_HIDDEN_STRING(String8, 0x08, ('6')('2')('C')('D')('6')('9')('7')('3')('B')('C')('3')('B')('D')('D')('8')('0'))

std::string KleverKeys::get(std::string id) {

	if(id == "90A4790D5BCBCC3721DF274227D41DA7333490CF20F2A2A0124C5D913AAAB1C") {
		return GetString1();
	} else if(id == "D7E34F0F2174178D421941F07B3B2D664D4FF1E89F4240468D007BB293824A48") {
		return GetString2();
	} else if(id == "20D76B4A7CE41E94F8AA4380F0C10C89C250DEB6B9D6C1D4D0E66E8ABB622EBA") {
		return GetString3();
	} else if(id == "D6ABA36146198EBA86A60034AD2D5AAA51B700DD87D675F714EBBA70A09460D7") {
		return GetString4();
	} else if(id == "81CBCC2306B60F43D3B49C2CA87791ACCEE175DA302DCFAA3244EB9EC7E74C48") {
		return GetString5();
	} else if(id == "F9EE3750F373FB0C874791F42D9660DC4428EA9C1FC83B5E1BA0DD0302F4D4AA") {
		return GetString6();
	} else if(id == "B1443F0FA3B179670433003D8845B0A262FF2936DD5F2F1B405791AC5275F2FF") {
		return GetString7();
	} else if(id == "DD60588BF2CA05576F3DBFE92B5187BA9D2A953162A888B3168D2B0FBC6175D") {
		return GetString8();
	}


	//return new HexSecureRandom();
	return "";


}
